### ISSUE TITLE
pymongo dependency

### ISSUE THREAD

**Issue by noisecapella** [openedx/opaque-keys#83]
It looks like opaque-keys lists `pymongo` as a dependency in `setup.py` but I don't see it referenced in the code base. Is this dependency still necessary? Just curious, thanks!

**Comment by feanil** [comment]
It looks like we use the `bson` module from pymongo and that's why it's a dependency.  The dependency needs an update but it is necessary.  We can't go to the `bson` git dependency instead because other upstream projects use the pymongo library and if both are installed, they will both provide the `bson` module which will complicate the installation and may cause unexpected behavior based on which one is installed last.  So we'll stick with the pymongo dependency in this repo.
